<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Snooper\Snooper.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Fonts\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shaders\**\*" />
      <None Remove="Fonts\**\*" />
  
      <EmbeddedResource Include="Shaders\**\*" />
      <EmbeddedResource Include="Fonts\**\*" />
    </ItemGroup>

</Project>
