layout(local_size_x = 32) in;

shared uint sMinVisible[32];
shared uint sMaxVisible[32];
shared float sClosestDist[32];
shared uint sAnyVisible[32];

struct PrimitiveDescriptor
{
    vec3 center;
    float sphereRadius;
    vec3 extents;
    uint maxLod;
    uvec4 firstIndex[2]; // EBO offsets for each LOD
    uvec4 baseVertex[2]; // VBO offsets for each LOD
    vec4 screenSize[2];
    uvec4 sectionCount[2]; // number of sections for each LOD
    uvec4 sectionOffset[2]; // section offsets for each LOD in SectionDescriptorsBuffer
};

struct SectionDescriptor
{
    uint firstIndex;
    uint count;
    uint materialIndex;
};

struct PerInstanceData
{
    mat4 matrix;
};

struct DrawElementsIndirectCommand // 1 draw command per section per model in LOD 0
{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
    uint originalInstanceCount;
    uint originalBaseInstance;
    uint modelId; // model offset in PrimitiveDescriptorsBuffer
    uint sectionId; // section index in the current model (0-X)
};

layout(std430, binding = 0) readonly buffer PerInstanceDataBuffer
{
    PerInstanceData uInstanceDataBuffer[];
};

layout(std430, binding = 1) readonly buffer PrimitiveDescriptorsBuffer
{
    PrimitiveDescriptor uPrimitiveDescriptors[];
};

layout(std430, binding = 2) buffer SectionDescriptorsBuffer
{
    SectionDescriptor uSectionDescriptors[];
};

layout(std430, binding = 3) buffer DrawCommandBuffer
{
    DrawElementsIndirectCommand uIndirectDrawCommands[];
};

uniform vec4 uFrustumPlanes[6];
uniform mat4 uProjectionMatrix;
uniform vec3 uCameraPosition;

bool isVisible(vec3 center, vec3 extents)
{
    bool isInside = true;
    for (int i = 0; i < 6; ++i)
    {
        vec4 plane = uFrustumPlanes[i];
        vec3 normal = plane.xyz;
        float d = plane.w;
        
        float r = dot(abs(normal), extents);
        float s = dot(normal, center) + d;
        if (s < -r)
        {
            isInside = false;
            break;
        }
    }
    return isInside;
}

bool equals(DrawElementsIndirectCommand a, DrawElementsIndirectCommand b)
{
    return
        a.baseInstance == b.baseInstance &&
        a.instanceCount == b.instanceCount &&
        a.count == b.count &&
        a.firstIndex == b.firstIndex &&
        a.baseVertex == b.baseVertex;
}

void main()
{
    uint drawId = gl_WorkGroupID.x;
    uint threadId = gl_LocalInvocationID.x;
    uint threadCount = gl_WorkGroupSize.x;
    
    if (drawId >= uIndirectDrawCommands.length()) return;

    DrawElementsIndirectCommand cmd = uIndirectDrawCommands[drawId];
    PrimitiveDescriptor primitive = uPrimitiveDescriptors[cmd.modelId];
    uint instanceCount = cmd.originalInstanceCount;
    uint baseInstance = cmd.originalBaseInstance;

    uint localMin = 0xFFFFFFFFu;
    uint localMax = 0;
    float localClosest = 3.402823e+38;
    uint localAny = 0u;

    for (uint j = threadId; j < instanceCount; j += threadCount)
    {
        mat4 modelMatrix = uInstanceDataBuffer[baseInstance + j].matrix;

        vec3 worldCenter = (modelMatrix * vec4(primitive.center, 1.0)).xyz;
        mat3 m = mat3(modelMatrix);
        vec3 worldExtents = vec3(
            dot(abs(m[0]), primitive.extents),
            dot(abs(m[1]), primitive.extents),
            dot(abs(m[2]), primitive.extents)
        );

        if (isVisible(worldCenter, worldExtents))
        {
            localMin = min(localMin, j);
            localMax = max(localMax, j);
            localClosest = min(localClosest, length(uCameraPosition - worldCenter));
            localAny = 1u;
        }
    }

    sMinVisible[threadId] = localMin;
    sMaxVisible[threadId] = localMax;
    sClosestDist[threadId] = localClosest;
    sAnyVisible[threadId] = localAny;
    barrier();

    // reduction
    for (uint offset = threadCount / 2u; offset > 0u; offset >>= 1u)
    {
        if (threadId < offset)
        {
            sMinVisible[threadId] = min(sMinVisible[threadId], sMinVisible[threadId + offset]);
            sMaxVisible[threadId] = max(sMaxVisible[threadId], sMaxVisible[threadId + offset]);
            sClosestDist[threadId] = min(sClosestDist[threadId], sClosestDist[threadId + offset]);
            sAnyVisible[threadId] |= sAnyVisible[threadId + offset];
        }
        barrier();
    }

    if (threadId != 0)
    {
        return;
    }

    DrawElementsIndirectCommand newCmd = cmd;
    if (sAnyVisible[0] == 1u)
    {
        newCmd.baseInstance = baseInstance + sMinVisible[0];
        newCmd.instanceCount = sMaxVisible[0] - sMinVisible[0] + 1;
        
        // if primitive has at least 2 lods, switch based on screen size
        if (primitive.maxLod > 0)
        {
            float screenRadius = primitive.sphereRadius * uProjectionMatrix[1][1] / sClosestDist[0];
            float screenSize = screenRadius * 2.0;

            uint chosenLod = 0u;
            for (uint i = 1u; i <= primitive.maxLod; ++i)
            {
                float threshold = primitive.screenSize[i / 4u][i % 4u];
                if (screenSize < threshold)
                {
                    chosenLod = i;
                    break;
                }
            }

            uint lod = clamp(chosenLod, 0u, primitive.maxLod);
            uint lodGroup = lod / 4u;
            uint lodSub = lod % 4u;

            uint sectionCount = primitive.sectionCount[lodGroup][lodSub];
            if (cmd.sectionId >= sectionCount)
            {
                newCmd.instanceCount = 0;
            }
            else
            {
                uint sectionOffset = primitive.sectionOffset[lodGroup][lodSub] + cmd.sectionId;
                SectionDescriptor section = uSectionDescriptors[sectionOffset];
                
                newCmd.count = section.count;
                newCmd.firstIndex = primitive.firstIndex[lodGroup][lodSub] + section.firstIndex;
                newCmd.baseVertex = primitive.baseVertex[lodGroup][lodSub];
            }
        }
    }
    else
    {
        newCmd.instanceCount = 0;
    }
    
    if (!equals(cmd, newCmd))
    {
        uIndirectDrawCommands[drawId].count         = newCmd.count;
        uIndirectDrawCommands[drawId].instanceCount = newCmd.instanceCount;
        uIndirectDrawCommands[drawId].firstIndex    = newCmd.firstIndex;
        uIndirectDrawCommands[drawId].baseVertex    = newCmd.baseVertex;
        uIndirectDrawCommands[drawId].baseInstance  = newCmd.baseInstance;
    }
}
